name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Install Google Cloud SDK
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project carbide-acre-451700-g8
          
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh

      - name: Get PR Details
        run: |
          gh auth status  # Check authentication
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          echo "Fetching PR $PR_NUMBER from $REPO"
          CHANGED_FILES=$(gh pr view $PR_NUMBER --json files -q '.files[].path')
          echo "Changed files: $CHANGED_FILES"
          echo "$CHANGED_FILES" > pr_files.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug File Structure
        run: ls -R $GITHUB_WORKSPACE

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AI Review
        run: python $GITHUB_WORKSPACE/ai_pr_review.py pr_content.txt

